//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKKH_Module.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAPANGOPY
    {
        public int maDAGY { get; set; }
        public string gopyKH { get; set; }
        public Nullable<int> maCH { get; set; }
    
        public virtual CAUHOI CAUHOI { get; set; }
    }
}
