//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKKH_Module.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_THI
    {
        public int ID { get; set; }
        public int maCD { get; set; }
        public int maDA { get; set; }
        public string maKH { get; set; }
    }
}
