//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YKKH_Module.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRUNGTHUONG
    {
        public int maTT { get; set; }
        public string maCD { get; set; }
        public string maKH { get; set; }
        public Nullable<int> songuoithamgia { get; set; }
        public Nullable<int> socaudung { get; set; }
    }
}
